# fly.toml app configuration file generated for visulinx-api on 2024-11-22T08:30:50-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'visulinx-api'
primary_region = 'sjc'

[build]

[deploy]
  release_command = 'uv run alembic upgrade head'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
