# fly.toml app configuration file generated for fastzeroapp on 2023-12-14T03:31:43-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "visulinx-api"
primary_region = "sjc"

[build]

[deploy]
  release_command = 'poetry run task migrate'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

