"""update files table

Revision ID: f6b2d59ed89a
Revises: 90a4f1ff4dfe
Create Date: 2024-12-21 10:56:03.966818

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f6b2d59ed89a'
down_revision: Union[str, None] = '90a4f1ff4dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('contents', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('files', sa.Column('processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'processed_at')
    op.drop_column('files', 'updated_at')
    op.drop_column('files', 'contents')
    # ### end Alembic commands ###
