"""add deleted_at to projects

Revision ID: 90a4f1ff4dfe
Revises: e1f919c1c0d4
Create Date: 2024-11-26 09:18:11.085301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a4f1ff4dfe'
down_revision: Union[str, None] = 'e1f919c1c0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deleted_at')
    # ### end Alembic commands ###
