"""add contents to file table

Revision ID: 68de9da0961b
Revises: 90a4f1ff4dfe
Create Date: 2024-12-21 08:40:42.825570

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '68de9da0961b'
down_revision: Union[str, None] = '90a4f1ff4dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('contents', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'contents')
    # ### end Alembic commands ###
